services:
  wordpress:
    container_name: wp-franken-prod
    build:
      context: .
      dockerfile: docker/prod/Dockerfile
      args:
        WP_VERSION: ${WP_VERSION}
    ports:
      - "${HTTP_PORT}:80"
      # - "${HTTPS_PORT}:443"
    env_file:
      - .env
    environment:
      DOMAIN: "${DOMAIN}"
      WORDPRESS_DB_HOST: "${DB_HOST}:${DB_PORT}"
      WORDPRESS_DB_NAME: "${DB_NAME}"
      WORDPRESS_DB_USER: "${DB_USER}"
      WORDPRESS_DB_PASSWORD: "${DB_PASSWORD}"
      APP_ENV: "${APP_ENV}"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      # uploads persist (recommended)
      - wp_uploads:/app/public/wp-content/uploads
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:
  wp_uploads: