services:
  wordpress:
    container_name: wp-franken-dev
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    ports:
      - "${HTTP_PORT}:80"
    env_file:
      - .env
    volumes:
      - ./src:/app/public
      - ./docker/dev/Caddyfile:/etc/frankenphp/Caddyfile:ro
      - ./docker/dev/php.ini:/usr/local/etc/php/conf.d/99-dev.ini:ro
    environment:
      WORDPRESS_DB_HOST: "${DB_HOST}:${DB_PORT}"
      WORDPRESS_DB_NAME: "${DB_NAME}"
      WORDPRESS_DB_USER: "${DB_USER}"
      WORDPRESS_DB_PASSWORD: "${DB_PASSWORD}"
    restart: unless-stopped